# Server configuration
server:
   port: 8082
   servlet:
      context-path: /profile
      encoding:
         charset: UTF-8
         enabled: true
         force: true

# Spring configuration
spring:
   application:
      name: profile-service
   neo4j:
      uri: ${NEO4J_URI:bolt://localhost:7687}
      authentication:
         username: ${NEO4J_USERNAME:neo4j}
         password: ${NEO4J_PASSWORD:admin@123}
   kafka:
      properties:
         security.protocol: PLAINTEXT
      producer:
         bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
         bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
         auto-offset-reset: earliest
         group-id: profile-service-group
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
         properties:
            spring.json.trusted.packages: "*"
            spring.json.value.default.type: "com.tth.commonlibrary.event.dto.NotificationEvent"